# Generated by Django 4.2.16 on 2024-09-24 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('subcategory_id', models.AutoField(db_column='subcategory_id', primary_key=True, serialize=False)),
                ('subcategory_name', models.CharField(db_column='subcategory_name', default='', max_length=255)),
                ('subcategory_description', models.CharField(db_column='subcategory_description', default='', max_length=255)),
                ('subcategory_category_vo', models.ForeignKey(db_column='subcategory_category_id', on_delete=django.db.models.deletion.CASCADE, to='Category.category')),
            ],
            options={
                'db_table': 'subcategory_table',
            },
        ),
    ]
