# Generated by Django 4.2.16 on 2024-09-24 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Category', '0001_initial'),
        ('SubCategory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(db_column='product_id', primary_key=True, serialize=False)),
                ('product_name', models.CharField(db_column='product_name', default='', max_length=255)),
                ('product_description', models.CharField(db_column='product_description', default='', max_length=255)),
                ('product_price', models.FloatField(db_column='product_price', default=0)),
                ('product_image_name', models.ImageField(db_column='product_image_name', default='', max_length=255, upload_to='static/product/')),
                ('product_category', models.ForeignKey(db_column='product_category_id', on_delete=django.db.models.deletion.CASCADE, to='Category.category')),
                ('product_subcategory', models.ForeignKey(db_column='product_subcategory_id', on_delete=django.db.models.deletion.CASCADE, to='SubCategory.subcategory')),
            ],
            options={
                'db_table': 'product_table',
            },
        ),
    ]
